Menu.create(navigation_name: "Roles", controller_name: "roles", icon: "ti-id-badge")
Menu.create(navigation_name: "Empleados", controller_name: "employees", icon: 'ti-user')
Menu.create(navigation_name: "Laboratorios", controller_name: "laboratories", icon: 'ti-home')
Menu.create(navigation_name: "Clientes", controller_name: "clients", icon: 'ti-user')
Menu.create(navigation_name: "Parametros del sistema", controller_name: "system_parameters", icon: 'ti-write')
Menu.create(navigation_name: "Auditoria", controller_name: "audits", icon: 'ti-write')
Menu.create(navigation_name: "Metodos de Ensayo", controller_name: "sample_methods", icon: 'ti-panel')
Menu.create(navigation_name: "Categoria de muestra", controller_name: "sample_categories", icon: 'ti-panel')
Menu.create(navigation_name: 'Inventario', controller_name: 'inventories', icon: 'ti-package')
Menu.create(navigation_name: "Servicios", controller_name: "client_services", icon: 'ti-panel')
Menu.create(navigation_name: "Servicios", controller_name: "employee_services", icon: 'ti-panel')
Menu.create(navigation_name: "Proformas", controller_name: "employee_quotations", icon: 'ti-panel')
Menu.create(navigation_name: "Proformas", controller_name: "client_quotations", icon: 'ti-panel')
Menu.create(navigation_name: "Custodias asignadas", controller_name: "employee_custody_orders", icon: 'ti-hummer')
Menu.create(navigation_name: "Ordenes de custodia", controller_name: "supervisor_custody_orders", icon: 'ti-hummer')
